### PR TITLE
Add Decode.pair

### PR DESCRIPTION
**Pull request by copy**
Add `pair : 'a decoder -> 'b decoder -> ('a * 'b) decoder` to decode tuples from json arrays with two elements (of potentially different types).

### CODE REVIEW

**Comment by glennsl** [comment]
Hi. Sorry for the delay with this. I was a bit unsure because `pair` is a bit of an indirect and foreign concept in both ReasonML and JS/JSON, and while it seems like it would be very useful when you do need it, I'm not sure how common of an occurrence that would be.

I've come down in favor of merging it though, but would like it to be tested. Could you add a test suite similar to the others in `__tests__/json_decode_test.ml`?

**Comment by copy** [comment]
@glennsl Done (originally I skipped over the `__tests__` directory due to its odd name and added a test in examples)

**Comment by glennsl** [comment]
Great, thanks!

**Comment by tcoopman** [comment]
Can this be published?

**Comment by glennsl** [comment]
@tcoopman I'd like to get some other changes in first, but I should be able to get a release out within a day.

**Comment by glennsl** [comment]
@tcoopman Done.

**Pull request merged**
